### ISSUE TITLE
后台服务启动失败：无法连接远程服务器：未知插件gq-client

### ISSUE THREAD

**Issue by yhwfr1** [cbeuw/GoQuiet-android#1]
gq-client-0.0.1.apk，报错，
“后台服务启动失败：无法连接远程服务器：未知插件gq-client”

![error -](https://user-images.githubusercontent.com/11403504/38170700-6b1869da-35be-11e8-8ef6-74e142c8f37e.jpg)

**Comment by hbxntsxw** [comment]
我的可以启动和连接，但是点测试网络后一直显示测试，也不能上网。电脑上是可以的，不过很不稳定，服务端经常自动退出。

**Comment by cbeuw** [comment]
@yhwfr1 
Duplicate of https://github.com/shadowsocks/shadowsocks-android/issues/1091#issuecomment-288420797

**Comment by cbeuw** [comment]
@hbxntsxw 
服务器退出的问题已在v1.1.2里解决：https://github.com/cbeuw/GoQuiet/issues/25

我自己的手机上也有同样的问题，但是断开再连几次之后就好了。奇怪的是在电脑的模拟器上没有这个情况，所以我怀疑是NDK toolchain的问题。

**Comment by hbxntsxw** [comment]
@cbeuw 谢谢你的回复！我断开重连也不行。服务端用的就是v1.1.2，我怀疑是服务器超售严重，内存不足退出了。请问服务端有输出日志的功能吗？谢谢！

**Comment by cbeuw** [comment]
@hbxntsxw 
想保存输出可以用[独立模式](https://github.com/cbeuw/GoQuiet#standalone-mode)+[nohup](https://unix.stackexchange.com/questions/45913/is-there-a-way-to-redirect-nohup-output-to-a-log-file-other-than-nohup-out)。 问题复现以后请在GoQuiet开个issue，谢谢！

**Comment by yhwfr1** [comment]
这个问题的确的解决方法是，在“权限管理”“后台管理”中设置成“允许后台运行”（缺省是“智能后台”）
另外，我还在Shadowsocks的设置选项里，用root权限打开“TCP Fast Open”。

但是，之后仍然无法正常连接，测试连接时报错，另开一个issue。

**Comment by hbxntsxw** [comment]
@cbeuw 已经开了个issue https://github.com/cbeuw/GoQuiet/issues/29
